name: Restart Discord Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Alle 6 Stunden
  workflow_dispatch:  # Ermöglicht manuellen Start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Code aus dem Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. GitHub Token einrichten (für den Zugriff auf private Repositories)
      - name: Set up GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.LOG_TOKEN }}
        run: |
          echo "Setting up GitHub token for access to the repository"

      # 3. Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. `log_channels.json` Datei aus dem GitHub Repository herunterladen
      - name: Load log_channels.json from GitHub repository
        run: |
          curl -H "Authorization: token ${{ secrets.LOG_TOKEN }}" \
               -L https://raw.githubusercontent.com/Wyld/Mein-DiscordBot/main/log_channels.json \
               -o log_channels.json
          echo "Verifiziere heruntergeladene Datei..."
          python -c "import json; json.load(open('log_channels.json'))"

      # 6. `warehouses.json` Datei aus dem GitHub Repository herunterladen
      - name: Load warehouses.json from GitHub repository
        run: |
          curl -H "Authorization: token ${{ secrets.LOG_TOKEN }}" \
               -L https://raw.githubusercontent.com/Wyld/Mein-DiscordBot/main/warehouses.json \
               -o warehouses.json || echo "{}" > warehouses.json
          echo "Verifiziere heruntergeladene Datei..."
          python -c "import json; json.load(open('warehouses.json'))"

      # 7. Discord Bot ausführen
      - name: Run Discord Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python main.py

      # 8. Änderungen an `log_channels.json` und `warehouses.json` speichern und in das GitHub-Repository pushen
      - name: Save updated JSON files to GitHub repository
        run: |
          # Git konfigurieren
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Änderungen vornehmen
          echo "# Update $(date)" >> warehouses.json
          
          # Überprüfen, ob es Änderungen gibt
          git add log_channels.json warehouses.json
          git status  # Zeigt an, ob Git Änderungen erkennt
          git diff --cached  # Zeigt die Änderungen an, die für den Commit vorgesehen sind
          
          # Falls Änderungen vorhanden sind, committen und pushen
          git commit -m "Update log_channels.json and warehouses.json" || echo "No changes to commit"
          
          # Falls Änderungen vorhanden sind, pushen
          git push https://x-access-token:${{ secrets.LOG_TOKEN }}@github.com/Wyld/Mein-DiscordBot.git HEAD:main
        continue-on-error: true  # Falls keine Änderungen vorgenommen wurden, wird dieser Schritt übersprungen
