name: Restart Discord Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Alle 6 Stunden
  workflow_dispatch:  # Ermöglicht manuellen Start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up logging
        run: |
          mkdir -p logs
          export LOG_FILE="logs/bot.log"
          touch $LOG_FILE
          tail -f $LOG_FILE &  # Protokolle überwachen

      - name: Run Discord Bot in background
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          nohup python main.py > bot.log 2>&1 &
